{"error":{"code":101,"message":"Object not found."},"level":"error","message":"Error generating response. ParseError { code: 101, message: 'Object not found.' }","timestamp":"2018-07-12T08:18:24.689Z"}
{"code":101,"message":"Object not found.","level":"error","timestamp":"2018-07-12T08:18:24.693Z"}
{"error":{"code":101,"message":"Object not found."},"level":"error","message":"Error generating response. ParseError { code: 101, message: 'Object not found.' }","timestamp":"2018-07-12T08:18:25.798Z"}
{"code":101,"message":"Object not found.","level":"error","timestamp":"2018-07-12T08:18:25.799Z"}
{"error":{"code":101,"message":"Object not found."},"level":"error","message":"Error generating response. ParseError { code: 101, message: 'Object not found.' }","timestamp":"2018-07-12T08:18:27.687Z"}
{"code":101,"message":"Object not found.","level":"error","timestamp":"2018-07-12T08:18:27.687Z"}
{"error":{"code":101,"message":"Object not found."},"level":"error","message":"Error generating response. ParseError { code: 101, message: 'Object not found.' }","timestamp":"2018-07-12T08:18:29.548Z"}
{"code":101,"message":"Object not found.","level":"error","timestamp":"2018-07-12T08:18:29.549Z"}
{"error":{"code":111,"message":"schema mismatch for MainChat.user; expected Object but got Pointer<_User>"},"level":"error","message":"Error generating response. ParseError {\n  code: 111,\n  message: 'schema mismatch for MainChat.user; expected Object but got Pointer<_User>' }","timestamp":"2018-07-12T09:17:36.970Z"}
{"code":111,"message":"schema mismatch for MainChat.user; expected Object but got Pointer<_User>","level":"error","timestamp":"2018-07-12T09:17:36.971Z"}
{"error":{"code":111,"message":"schema mismatch for MainChat.user; expected Object but got Pointer<_User>"},"level":"error","message":"Error generating response. ParseError {\n  code: 111,\n  message: 'schema mismatch for MainChat.user; expected Object but got Pointer<_User>' }","timestamp":"2018-07-12T09:19:05.616Z"}
{"code":111,"message":"schema mismatch for MainChat.user; expected Object but got Pointer<_User>","level":"error","timestamp":"2018-07-12T09:19:05.618Z"}
{"error":{"code":111,"message":"schema mismatch for MainChat.user; expected Object but got Pointer<_User>"},"level":"error","message":"Error generating response. ParseError {\n  code: 111,\n  message: 'schema mismatch for MainChat.user; expected Object but got Pointer<_User>' }","timestamp":"2018-07-12T09:20:32.762Z"}
{"code":111,"message":"schema mismatch for MainChat.user; expected Object but got Pointer<_User>","level":"error","timestamp":"2018-07-12T09:20:32.764Z"}
{"error":{"code":111,"message":"schema mismatch for MainChat.user; expected Object but got Pointer<_User>"},"level":"error","message":"Error generating response. ParseError {\n  code: 111,\n  message: 'schema mismatch for MainChat.user; expected Object but got Pointer<_User>' }","timestamp":"2018-07-12T09:20:58.475Z"}
{"code":111,"message":"schema mismatch for MainChat.user; expected Object but got Pointer<_User>","level":"error","timestamp":"2018-07-12T09:20:58.476Z"}
{"error":{"code":111,"message":"schema mismatch for MainChat.user; expected Object but got Pointer<_User>"},"level":"error","message":"Error generating response. ParseError {\n  code: 111,\n  message: 'schema mismatch for MainChat.user; expected Object but got Pointer<_User>' }","timestamp":"2018-07-12T09:21:20.658Z"}
{"code":111,"message":"schema mismatch for MainChat.user; expected Object but got Pointer<_User>","level":"error","timestamp":"2018-07-12T09:21:20.660Z"}
{"error":{"code":111,"message":"schema mismatch for MainChat.user; expected Object but got Pointer<_User>"},"level":"error","message":"Error generating response. ParseError {\n  code: 111,\n  message: 'schema mismatch for MainChat.user; expected Object but got Pointer<_User>' }","timestamp":"2018-07-12T09:21:45.178Z"}
{"code":111,"message":"schema mismatch for MainChat.user; expected Object but got Pointer<_User>","level":"error","timestamp":"2018-07-12T09:21:45.179Z"}
{"error":{"code":101,"message":"Object not found."},"level":"error","message":"Error generating response. ParseError { code: 101, message: 'Object not found.' }","timestamp":"2018-07-12T13:11:14.163Z"}
{"code":101,"message":"Object not found.","level":"error","timestamp":"2018-07-12T13:11:14.291Z"}
{"error":{"code":101,"message":"Object not found."},"level":"error","message":"Error generating response. ParseError { code: 101, message: 'Object not found.' }","timestamp":"2018-07-12T13:11:14.393Z"}
{"code":101,"message":"Object not found.","level":"error","timestamp":"2018-07-12T13:11:14.394Z"}
{"error":{"code":101,"message":"Object not found."},"level":"error","message":"Error generating response. ParseError { code: 101, message: 'Object not found.' }","timestamp":"2018-07-12T13:11:14.398Z"}
{"code":101,"message":"Object not found.","level":"error","timestamp":"2018-07-12T13:11:14.398Z"}
{"error":{"code":101,"message":"Object not found."},"level":"error","message":"Error generating response. ParseError { code: 101, message: 'Object not found.' }","timestamp":"2018-07-12T13:11:14.519Z"}
{"code":101,"message":"Object not found.","level":"error","timestamp":"2018-07-12T13:11:14.520Z"}
{"error":{"code":101,"message":"Object not found."},"level":"error","message":"Error generating response. ParseError { code: 101, message: 'Object not found.' }","timestamp":"2018-07-12T13:11:14.534Z"}
{"code":101,"message":"Object not found.","level":"error","timestamp":"2018-07-12T13:11:14.534Z"}
{"error":{"name":"MongoError","message":"interrupted at shutdown","ok":0,"errmsg":"interrupted at shutdown","code":11600,"codeName":"InterruptedAtShutdown"},"level":"error","message":"Error generating response. { MongoError: interrupted at shutdown\n    at queryCallback (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\cursor.js:244:25)\n    at I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:544:18\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'interrupted at shutdown',\n  ok: 0,\n  errmsg: 'interrupted at shutdown',\n  code: 11600,\n  codeName: 'InterruptedAtShutdown' }","timestamp":"2018-07-12T13:11:30.331Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: interrupted at shutdown\n    at queryCallback (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\cursor.js:244:25)\n    at I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:544:18\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'interrupted at shutdown',\n  ok: 0,\n  errmsg: 'interrupted at shutdown',\n  code: 11600,\n  codeName: 'InterruptedAtShutdown' } MongoError: interrupted at shutdown\n    at queryCallback (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\cursor.js:244:25)\n    at I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:544:18\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2018-07-12T13:11:30.333Z"}
{"error":{"name":"MongoError","message":"interrupted at shutdown","ok":0,"errmsg":"interrupted at shutdown","code":11600,"codeName":"InterruptedAtShutdown"},"level":"error","message":"Error generating response. { MongoError: interrupted at shutdown\n    at queryCallback (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\cursor.js:244:25)\n    at I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:544:18\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'interrupted at shutdown',\n  ok: 0,\n  errmsg: 'interrupted at shutdown',\n  code: 11600,\n  codeName: 'InterruptedAtShutdown' }","timestamp":"2018-07-12T13:11:30.334Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: interrupted at shutdown\n    at queryCallback (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\cursor.js:244:25)\n    at I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:544:18\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'interrupted at shutdown',\n  ok: 0,\n  errmsg: 'interrupted at shutdown',\n  code: 11600,\n  codeName: 'InterruptedAtShutdown' } MongoError: interrupted at shutdown\n    at queryCallback (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\cursor.js:244:25)\n    at I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:544:18\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2018-07-12T13:11:30.335Z"}
{"error":{"name":"MongoError","message":"interrupted at shutdown","ok":0,"errmsg":"interrupted at shutdown","code":11600,"codeName":"InterruptedAtShutdown"},"level":"error","message":"Error generating response. { MongoError: interrupted at shutdown\n    at queryCallback (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\cursor.js:244:25)\n    at I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:544:18\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'interrupted at shutdown',\n  ok: 0,\n  errmsg: 'interrupted at shutdown',\n  code: 11600,\n  codeName: 'InterruptedAtShutdown' }","timestamp":"2018-07-12T13:11:30.409Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: interrupted at shutdown\n    at queryCallback (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\cursor.js:244:25)\n    at I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:544:18\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'interrupted at shutdown',\n  ok: 0,\n  errmsg: 'interrupted at shutdown',\n  code: 11600,\n  codeName: 'InterruptedAtShutdown' } MongoError: interrupted at shutdown\n    at queryCallback (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\cursor.js:244:25)\n    at I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:544:18\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2018-07-12T13:11:30.410Z"}
{"error":{"name":"MongoError","message":"interrupted at shutdown","ok":0,"errmsg":"interrupted at shutdown","code":11600,"codeName":"InterruptedAtShutdown"},"level":"error","message":"Error generating response. { MongoError: interrupted at shutdown\n    at queryCallback (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\cursor.js:244:25)\n    at I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:544:18\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'interrupted at shutdown',\n  ok: 0,\n  errmsg: 'interrupted at shutdown',\n  code: 11600,\n  codeName: 'InterruptedAtShutdown' }","timestamp":"2018-07-12T13:11:30.411Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: interrupted at shutdown\n    at queryCallback (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\cursor.js:244:25)\n    at I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:544:18\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n  name: 'MongoError',\n  message: 'interrupted at shutdown',\n  ok: 0,\n  errmsg: 'interrupted at shutdown',\n  code: 11600,\n  codeName: 'InterruptedAtShutdown' } MongoError: interrupted at shutdown\n    at queryCallback (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\cursor.js:244:25)\n    at I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:544:18\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","timestamp":"2018-07-12T13:11:30.412Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:505:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:329:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-07-12T13:11:32.996Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:505:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:329:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:505:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:329:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)","timestamp":"2018-07-12T13:11:32.998Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:505:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:329:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-07-12T13:11:32.999Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:505:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:329:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:505:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:329:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)","timestamp":"2018-07-12T13:11:32.999Z"}
{"error":{"name":"MongoNetworkError","message":"failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:505:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:329:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-07-12T13:11:33.001Z"}
{"level":"error","message":"Uncaught internal server error. { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:505:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:329:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n  name: 'MongoNetworkError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:505:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:329:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)","timestamp":"2018-07-12T13:11:33.002Z"}
{"message":"error getting auth for sessionToken","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:505:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:329:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)","level":"error","timestamp":"2018-07-12T13:11:33.003Z"}
{"message":"error getting auth for sessionToken","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:505:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:329:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)","level":"error","timestamp":"2018-07-12T13:11:33.004Z"}
{"message":"error getting auth for sessionToken","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:505:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:329:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)","level":"error","timestamp":"2018-07-12T13:11:35.155Z"}
{"message":"error getting auth for sessionToken","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:505:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:329:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)","level":"error","timestamp":"2018-07-12T13:11:35.155Z"}
{"message":"error getting auth for sessionToken","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:505:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:329:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)","level":"error","timestamp":"2018-07-12T13:11:35.156Z"}
{"message":"error getting auth for sessionToken","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\topologies\\server.js:505:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at Connection.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\pool.js:329:12)\n    at Object.onceWrapper (events.js:317:30)\n    at emitTwo (events.js:126:13)\n    at Connection.emit (events.js:214:7)\n    at Socket.<anonymous> (I:\\zWebBased\\server\\node_modules\\parse-server\\node_modules\\mongodb-core\\lib\\connection\\connection.js:245:50)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)","level":"error","timestamp":"2018-07-12T13:11:35.157Z"}
